name: $(Build.BuildId)

# Trigger on push to development
trigger:
- development

pool:
  vmImage: 'Ubuntu-16.04'

# Note: github_pat should be configured as an environment variable in devops
#   -> create github pat here: https://github.com/settings/tokens
#   -> Create environment variable in dev.azure.com under pipelines -> edit (right top) -> variables (right top triple dots) -> called github_pat -> click the lock
variables:
  projectName: bootcamp-slides
  registryServerName: '$(registryName).azurecr.io'
  imageName: '$(projectName)'


steps:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azdevops&tabs=schema#checkout

- script: |
    curl -L https://github.com/marp-team/marp-cli/releases/download/v0.12.1/marp-cli-v0.12.1-linux.tar.gz -o marp-cli.tar.gz
    tar zxfvp marp-cli.tar.gz
  displayName: '[MARP] Install MARP CLI'

- script: |
    mkdir html;
    ./marp -I $(system.defaultWorkingDirectory)/$(projectName) -o html/;
  displayName: '[MARP] Build HTML'
  
- bash: docker build -f $(system.defaultWorkingDirectory)/$(projectName)/Dockerfile -t $(registryServerName)/$(imageName):$(build.buildId) $(system.defaultWorkingDirectory)/$(projectName)
  displayName: '[Docker] docker build'

- bash: |
    docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
    docker push $(registryServerName)/$(imageName):$(build.buildId)
  displayName: '[Docker] docker push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

- task: HelmInstaller@0
  displayName: 'Install Helm'
  inputs:
    helmVersion: 2.14.1

- bash: helm package --version $(build.buildId) --destination $(build.artifactStagingDirectory) $(system.defaultWorkingDirectory)/$(projectName)/charts/$(projectName)
  displayName: 'helm package'

- bash: az acr helm push -n $(registryName) -u $(registryLogin) -p $(registryPassword) $(build.artifactStagingDirectory)/$(projectName)-$(build.buildId).tgz
  displayName: 'az acr helm push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))